### ISSUE TITLE
Apple Silicon (M1) support?

### ISSUE THREAD

**Issue by joreilly** [kuuuurt/multiplatform-paging#23]
Are there plans to include support for running on M1 devices (supporting `iosSimulatorArm64` target)?

**Comment by kuuuurt** [comment]
Hi @joreilly! Of course there are. I have to admit, I haven't been maintaining this well since it has a small use case in my current projet. Top of my list is to upgrade Kotlin to 1.6.0 but I'm finding it hard to find time to work on these without compromising my rest to prevent burnout. PRs are definitely welcome if you'd like to add them :)

**Comment by joreilly** [comment]
No worries, definitely not urgent....I'll take a look and see if I can create PR for the change needed.

**Comment by kuuuurt** [comment]
@joreilly i released 0.4.6 for Kotlin 1.6.0 and added `iosSimulatorArm64` as a target. Not sure if it works though since I don't have an M1 machine but feel free to try it out and let me know

**Comment by joreilly** [comment]
That's great, thanks!  Will give it a go shortly

**Comment by joreilly** [comment]
Just tried it now and works great!  Changes to use that version (and generally to support M1) pushed to https://github.com/joreilly/MortyComposeKMM

**Comment by kuuuurt** [comment]
That's great to hear! Closing this issue now. 🙂
